lib/visitor_tracking_web/router.ex
defmodule VisitorTrackingWeb.Router do
  use VisitorTrackingWeb, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VisitorTrackingWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug VisitorTrackingWeb.Plugs.Auth
  end

  pipeline :api do
    plug CORSPlug,
      origin: [
        "https://www.vesita.local:4001",
        "https://0.0.0.0:4001",
        "https://visitor-tracking-staging.gigalixirapp.com",
        "https://vesita-prod.herokuapp.com",
        "https://www.vesita.ch"
      ]

    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
  end

  scope "/", VisitorTrackingWeb do
    pipe_through :browser

    get "/", CmsController, :homepage
    get "/v/:token", ProfileController, :verify_email
    get "/datenschutz", CmsController, :privacy
    get "/preise", CmsController, :prices
    get "/impressum", CmsController, :impressum
    get "/so-einfach-funktioniert-vesita", CmsController, :howto
    get "/login", SessionController, :new
    post "/sessions", SessionController, :create
    get "/phone_validation", RegistrationController, :phone_validation
    post "/phone_confirmation", RegistrationController, :phone_confirmation
    get "/qr/:uuid", QrController, :show
    get "/kontakt", ContactFormController, :new
  end

  scope "/password/", VisitorTrackingWeb do
    pipe_through :browser
    get "/", PasswordController, :reset_password_request_form
    post "/", PasswordController, :reset_password_request
    get "/:token", PasswordController, :reset_password
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :check_registered]

    post "/register", RegistrationController, :new
    post "/users", RegistrationController, :create
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user]

    delete "/logout", SessionController, :delete
    get "/new_token", RegistrationController, :new_token
    get "/phone_verification", RegistrationController, :phone_verification
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified]

    get "/expecting_verification", ProfileController, :expecting_verification
    resources "/events", EventController
    get "/events/:id/start_event", EventController, :start_event
    get "/events/:id/close_event", EventController, :close_event
    get "/events/:event_id/scan", ScanController, :show
    resources "/events/:event_id/emergency", EmergencyController, only: [:new, :create]
    get "/profile", ProfileController, :show
    get "/profile/qrcode", ProfileController, :show
  end

  scope "/events/:event_id/scanners", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]

    resources "/", ScannerController
  end

  scope "/events/:event_id/emergency", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]
    # resources "/", EmergencyController
  end

  # Other scopes may use custom stacks.
  scope "/api", VisitorTrackingWeb do
    pipe_through :api

    post "/scan/event_infos", ScanController, :event_infos
    post "/scan/user", ScanController, :user
    post "/scan/assign_visitor", ScanController, :assign_visitor
    post "/contact_forms/create", ContactFormController, :create
    post "/scan/insert_action", ScanController, :insert_action
    post "/registration/user", RegistrationApiController, :create
    post "/phone", RegistrationApiController, :verify_phone
    post "/password/reset", PasswordApiController, :reset_password
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:visitor_tracking, :developer_tools) == "true" do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: VisitorTrackingWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/visitor_tracking_web/views/layout_view.ex
defmodule VisitorTrackingWeb.LayoutView do
  use VisitorTrackingWeb, :view
  use PhoenixMetaTags.TagView
end

lib/visitor_tracking_web/templates/layout/alert.html.eex
<div class="alert notification is-info is-light" role="alert"><%= get_flash(@conn, :info) %></div>
<div class="alert notification is-danger is-light" role="alert"><%= get_flash(@conn, :error) %></div>

lib/visitor_tracking_web/templates/layout/app.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= render_tags_all(assigns[:meta_tags] || %{})%>
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "VisitorTracking", suffix: " · Phoenix Framework" %>
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <script src="https://kit.fontawesome.com/15181efa86.js" crossorigin="anonymous"></script>

    <!-- Hitsteps TRACKING CODE - Manual 2020-08-06 - DO NOT CHANGE -->
    <script type="text/javascript">(function(){var hstc=document.createElement('script'); hstc.src='https://log.hitsteps.com/track.php?code=0a564a4c375d68a25926ac5fff3b435e';hstc.async=true;var htssc = document.getElementsByTagName('script')[0];htssc.parentNode.insertBefore(hstc, htssc);})();
    </script><noscript><a href="http://www.hitsteps.com/"><img src="//log.hitsteps.com/track.php?mode=img&amp;code=0a564a4c375d68a25926ac5fff3b435e" alt="blog tracking" width="1" height="1" />blog statistics</a></noscript>
    <!-- Hitsteps TRACKING CODE - DO NOT CHANGE -->

    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

</head>
<body>

  <main role="main">
    <%= @inner_content %>
  </main>

  <%= render(VisitorTrackingWeb.LayoutView, "footer.html", conn: @conn) %>
</body>

lib/visitor_tracking_web/templates/layout/email.html.eex
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Email</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(VisitorTrackingWeb.Endpoint, "/css/email.css") %>"/>
</head>
<body style="background-color: #e9ecef;">

    <%= @inner_content %>

</body>
</html>

lib/visitor_tracking_web/templates/layout/footer.html.eex
<footer class="footer mt-6">
  <div class="content has-text-centered">
    <a href="/">
      <img src="<%= Routes.static_path(@conn, "/images/vesita-logo-full.svg") %>" width="150" alt="Vesita Logo full">
    </a>  

    <div class="footer-links mt-3">
      <%= link "Preise", to: Routes.cms_path(@conn, :prices), class: "button is-text" %>
      <%= link "Impressum", to: Routes.cms_path(@conn, :impressum), class: "button is-text" %>
      <%= link "Kontakt", to: Routes.contact_form_path(@conn, :new), class: "button is-text" %>
      <%= link "Datenschutz", to: Routes.cms_path(@conn, :privacy), class: "button is-text" %>
    </div>

    <p>Developed with <i class="fas fa-heart"></i></p>

  </div>
</footer>

lib/visitor_tracking_web/templates/layout/header.html.eex
<section class="hero is-medium is-info is-bold mb-6">
  <div class="hero-head">
    <%= render(VisitorTrackingWeb.LayoutView, "navigation.html", %{conn: @conn, current_user: @current_user}) %>
  </div>
</section>

<section>
  <div class="container">
    <%= render(VisitorTrackingWeb.LayoutView, "alert.html", conn: @conn) %>
  </div>
</section>

lib/visitor_tracking_web/templates/layout/live.html.leex
<main role="main" class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>
  <%= @inner_content %>
</main>

lib/visitor_tracking_web/templates/layout/navigation.html.eex
<nav class="navbar">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="<%= Routes.static_path(@conn, "/images/vesita-logo-text-white.svg") %>" width="100px" alt="Vesita Logo without icon">
      </a>
      <span class="navbar-burger burger" data-target="navMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navMenu" class="navbar-menu">
      <div class="navbar-end">
        <%= link "Anleitung", to: Routes.cms_path(@conn, :howto), class: "navbar-item" %>
        <%= link "Preise", to: Routes.cms_path(@conn, :prices), class: "navbar-item" %>

        <%= if @current_user do %>
          <%= link "Veranstaltungen", to: Routes.event_path(@conn, :index), class: "navbar-item" %>
          <%= link "Profil", to: Routes.profile_path(@conn, :show), class: "navbar-item" %>

          <div class="navbar-item has-dropdown is-hoverable">
            <a class="navbar-link">
              <span class="icon is-small">
                <i class="fas fa-user"></i>
              </span>
              <span><%= @current_user.firstname %></span>
            </a>

            <div class="navbar-dropdown">
              <%= link "Abmelden", to: Routes.session_path(@conn, :delete), method: :delete, class: "navbar-item" %>
            </div>
          </div>
        <% else %>

          <span class="navbar-item">
            <%= link to: "/phone_validation", class: "button is-warning" do %>
              <span>Registrieren</span>
            <% end %>
          </span>

          <span class="navbar-item">
            <%= link to: Routes.session_path(@conn, :new), class: "button is-info is-inverted" do %>
              <span class="icon is-small">
                <i class="fas fa-user"></i>
              </span>
              <span>Anmelden</span>
            <% end %>
          </span>
        <% end %>
      </div>
    </div>
  </div>
</nav>

lib/visitor_tracking_web/templates/layout/root.html.leex
<!DOCTYPE html>
<html lang="de">
  <%= @inner_content %>
</html>

lib/visitor_tracking_web/templates/layout/scanner.html.eex
<head>
  <meta charset="utf-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <%= render_tags_all(assigns[:meta_tags] || %{})%>
  <%= csrf_meta_tag() %>
  <%= live_title_tag assigns[:page_title] || "Home", suffix: " · Vesita" %>
  <link phx-track-static rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  <script defer phx-track-static type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  <script src="https://kit.fontawesome.com/15181efa86.js" crossorigin="anonymous"></script>

    <!-- Hitsteps TRACKING CODE - Manual 2020-08-06 - DO NOT CHANGE -->
    <script type="text/javascript">(function(){var hstc=document.createElement('script'); hstc.src='https://log.hitsteps.com/track.php?code=0a564a4c375d68a25926ac5fff3b435e';hstc.async=true;var htssc = document.getElementsByTagName('script')[0];htssc.parentNode.insertBefore(hstc, htssc);})();
    </script><noscript><a href="http://www.hitsteps.com/"><img src="//log.hitsteps.com/track.php?mode=img&amp;code=0a564a4c375d68a25926ac5fff3b435e" alt="blog tracking" width="1" height="1" />blog statistics</a></noscript>
    <!-- Hitsteps TRACKING CODE - DO NOT CHANGE -->

    <link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

</head>
<body>
  <%= @inner_content %>
</body>