lib/visitor_tracking_web/router.ex
defmodule VisitorTrackingWeb.Router do
  use VisitorTrackingWeb, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VisitorTrackingWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug VisitorTrackingWeb.Plugs.Auth
  end

  pipeline :api do
    plug CORSPlug,
      origin: [
        "https://www.vesita.local:4001",
        "https://0.0.0.0:4001",
        "https://visitor-tracking-staging.gigalixirapp.com",
        "https://vesita-prod.herokuapp.com",
        "https://www.vesita.ch"
      ]

    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
  end

  scope "/", VisitorTrackingWeb do
    pipe_through :browser

    get "/", CmsController, :homepage
    get "/v/:token", ProfileController, :verify_email
    get "/datenschutz", CmsController, :privacy
    get "/preise", CmsController, :prices
    get "/impressum", CmsController, :impressum
    get "/so-einfach-funktioniert-vesita", CmsController, :howto
    get "/login", SessionController, :new
    post "/sessions", SessionController, :create
    get "/phone_validation", RegistrationController, :phone_validation
    post "/phone_confirmation", RegistrationController, :phone_confirmation
    get "/qr/:uuid", QrController, :show
    get "/kontakt", ContactFormController, :new
  end

  scope "/password/", VisitorTrackingWeb do
    pipe_through :browser
    get "/", PasswordController, :reset_password_request_form
    post "/", PasswordController, :reset_password_request
    get "/:token", PasswordController, :reset_password
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :check_registered]

    post "/register", RegistrationController, :new
    post "/users", RegistrationController, :create
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user]

    delete "/logout", SessionController, :delete
    get "/new_token", RegistrationController, :new_token
    get "/phone_verification", RegistrationController, :phone_verification
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified]

    get "/expecting_verification", ProfileController, :expecting_verification
    resources "/events", EventController
    get "/events/:id/start_event", EventController, :start_event
    get "/events/:id/close_event", EventController, :close_event
    get "/events/:event_id/scan", ScanController, :show
    resources "/events/:event_id/emergency", EmergencyController, only: [:new, :create]
    get "/profile", ProfileController, :show
    get "/profile/qrcode", ProfileController, :show
  end

  scope "/events/:event_id/scanners", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]

    resources "/", ScannerController
  end

  scope "/events/:event_id/emergency", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]
    # resources "/", EmergencyController
  end

  # Other scopes may use custom stacks.
  scope "/api", VisitorTrackingWeb do
    pipe_through :api

    post "/scan/event_infos", ScanController, :event_infos
    post "/scan/user", ScanController, :user
    post "/scan/assign_visitor", ScanController, :assign_visitor
    post "/contact_forms/create", ContactFormController, :create
    post "/scan/insert_action", ScanController, :insert_action
    post "/registration/user", RegistrationApiController, :create
    post "/phone", RegistrationApiController, :verify_phone
    post "/password/reset", PasswordApiController, :reset_password
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:visitor_tracking, :developer_tools) == "true" do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: VisitorTrackingWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/visitor_tracking/events/action.ex
defmodule VisitorTracking.Events.Action do
  @moduledoc """
  User actions on an event.
  in -> user is in the venue
  out -> user has left the venue
  """
  use Ecto.Schema
  import Ecto.Changeset

  schema "event_visitor_actions" do
    belongs_to :event, VisitorTracking.Events.Event
    belongs_to :user, VisitorTracking.Accounts.User
    field :action, :string

    timestamps()
  end

  def changeset(action, params) do
    action
    |> cast(params, [:event_id, :user_id, :action])
    |> validate_required([:event_id, :user_id, :action])
    |> foreign_key_constraint(:event_id)
    |> foreign_key_constraint(:user_id)
  end
end

lib/visitor_tracking/events/event.ex
defmodule VisitorTracking.Events.Event do
  @moduledoc """
  User Schema module
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias VisitorTracking.{Accounts.User, Emergency}

  schema "events" do
    belongs_to :organiser, User
    field :closed, :boolean, default: false
    field :date_start, :naive_datetime
    field :name, :string
    field :status, :string
    field :venue, :string
    field :visitor_limit, :integer
    has_one :emergency, Emergency

    many_to_many :scanners, User, join_through: "event_scanners"

    many_to_many(
      :visitors,
      User,
      join_through: "events_visitors",
      on_replace: :delete
    )

    timestamps()
  end

  @doc false
  def changeset(event, attrs) do
    event
    |> cast(attrs, [
      :organiser_id,
      :name,
      :venue,
      :status,
      :closed,
      :date_start,
      :visitor_limit
    ])
    |> validate_required([:organiser_id, :name, :venue, :date_start, :visitor_limit])
  end

  @doc false
  def changeset_organiser(event, %{id: organiser_id} = _args) do
    event
    |> cast(%{organiser_id: organiser_id}, [:organiser_id])
    |> validate_required([:organiser_id])
  end
end

lib/visitor_tracking/events/events_visitors.ex
defmodule VisitorTracking.Events.Visitor do
  @moduledoc """
  Connects a user with an event.
  """
  use Ecto.Schema

  import Ecto.Changeset

  alias VisitorTracking.Accounts.User
  alias VisitorTracking.Events.Event

  @primary_key false
  schema "events_visitors" do
    belongs_to :event_id, Event, primary_key: true
    belongs_to :user_id, User, primary_key: true
    timestamps()
  end

  @required_fields ~w(event_id user_id)a
  def changeset(visitor, params \\ %{}) do
    visitor
    |> cast(params, @required_fields)
    |> validate_required(@required_fields)
    |> foreign_key_constraint(:event_id)
    |> foreign_key_constraint(:user_id)
    |> unique_constraint([:event, :user],
      name: :event_id_user_id_unique_index,
      message: "ALREADY_EXISTS"
    )
  end
end

lib/visitor_tracking/events/rules.ex
defmodule VisitorTracking.Events.Rules do
  @moduledoc """
  Event state machine.
  """

  alias __MODULE__

  defstruct state: "created"

  def new, do: {:ok, %Rules{}}

  def from_event(nil), do: %Rules{state: "error"}
  def from_event(event), do: %Rules{state: event.status}

  def check(%Rules{state: "created"} = _rule, :add_scanner),
    do: {:ok, %Rules{state: "created"}}

  def check(%Rules{state: "created"} = _rule, :delete_event),
    do: {:ok, %Rules{state: "created"}}

  def check(%Rules{state: "created"} = _rule, :start_event),
    do: {:ok, %Rules{state: "open"}}

  def check(%Rules{state: "open"} = _rule, :close_event),
    do: {:ok, %Rules{state: "closed"}}

  def check(%Rules{state: "open"} = _rule, :add_scanner),
    do: {:ok, %Rules{state: "open"}}

  def check(%Rules{state: "closed"} = _rule, :start_event),
    do: {:ok, %Rules{state: "open"}}

  def check(%Rules{state: "created"} = _rule, :archive_event),
    do: {:ok, %Rules{state: "archived"}}

  def check(%Rules{state: "closed"} = _rule, :archive_event),
    do: {:ok, %Rules{state: "archived"}}

  def check(%Rules{state: "open"} = _rule, :archive_event),
    do: {:ok, %Rules{state: "archived"}}

  def check(%Rules{state: "open"} = _rule, :add_visitor),
    do: {:ok, %Rules{state: "open"}}

  def check(_state, _action), do: :error
end

lib/visitor_tracking/events/scanner.ex
defmodule VisitorTracking.Events.Scanner do
  @moduledoc """
  Scanner Schema Module for event_scanners table
  """

  use Ecto.Schema
  import Ecto.Changeset

  schema "event_scanners" do
    belongs_to :event, VisitorTracking.Events.Event
    belongs_to :user, VisitorTracking.Accounts.User
    field :enabled, :boolean

    timestamps()
  end

  def changeset(scanner, attrs) do
    scanner
    |> cast(attrs, [:event_id, :user_id])
    |> validate_required([:event_id, :user_id])
    |> foreign_key_constraint(:event_id)
    |> foreign_key_constraint(:user_id)
  end
end

lib/visitor_tracking/events/visitor.ex
defmodule VisitorTracking.Events.Visitor do
  @moduledoc """
  Connects a user with an event.
  """
  use Ecto.Schema

  import Ecto.Changeset

  alias VisitorTracking.Accounts.User
  alias VisitorTracking.Events.Event

  @primary_key false
  schema "events_visitors" do
    belongs_to :event, Event, primary_key: true
    belongs_to :user, User, primary_key: true
  end

  @required_fields ~w(event_id user_id)a
  def changeset(visitor, params \\ %{}) do
    visitor
    |> cast(params, @required_fields)
    |> validate_required(@required_fields)
    |> foreign_key_constraint(:event_id)
    |> foreign_key_constraint(:user_id)
    |> unique_constraint([:event_id, :user_id],
      name: :events_visitors_pkey,
      message: "ALREADY_EXISTS"
    )
  end
end

lib/visitor_tracking_web/controllers/event_controller.ex
defmodule VisitorTrackingWeb.EventController do
  use VisitorTrackingWeb, :controller

  alias VisitorTracking.{Accounts, Events, Events.Event, Events.Rules, Emergencies}

  plug :check_if_organiser_or_scanner when action in [:show]

  plug :check_if_organiser
       when action in [:edit, :update, :start_event, :close_event, :delete]

  def index(conn, _params) do
    %{event_scanner: events} = Accounts.get_all_events_from_scanner(conn.assigns.current_user.id)
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = Events.change_event(%Event{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"event" => event_params}) do
    event_params
    |> Map.put("organiser_id", conn.assigns.current_user.id)
    |> Events.create_event()
    |> case do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Veranstaltung wurde erstellt.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    case Events.get_event(id) do
      nil ->
        conn
        |> put_flash(
          :error,
          "Nur der Veranstalter ist berechtigt, diese Veranstaltung anzusehen."
        )
        |> redirect(to: Routes.event_path(conn, :index))

      event ->
        render(conn, "show.html", %{
          event: event,
          visitors: Events.get_visitors_stats(event.id),
          scanners: Events.list_scanners(id),
          emergency: Emergencies.get_emergency_by_event_id(id)
        })
    end
  end

  def edit(conn, %{"id" => id}) do
    event = Events.get_event!(id, conn.assigns.current_user.id)
    changeset = Events.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Events.get_event!(id, conn.assigns.current_user.id)

    case Events.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = Events.get_event!(id, conn.assigns.current_user.id)
    {:ok, _event} = Events.delete_event(event)

    conn
    |> put_flash(:info, "Veranstaltung wurde gelöscht.")
    |> redirect(to: Routes.event_path(conn, :index))
  end

  def start_event(conn, %{"id" => id}) do
    with event <- Events.get_event!(id, conn.assigns.current_user.id),
         {:ok, rule} <- Rules.check(Rules.from_event(event), :start_event),
         {:ok, _event} <- Events.update_event(event, %{"status" => rule.state}) do
      conn
      |> put_flash(:info, "Status verändert.")
      |> redirect(to: Routes.event_path(conn, :show, id))
    else
      :error ->
        conn
        |> put_flash(:error, "Not allowed.")
        |> redirect(to: Routes.event_path(conn, :show, id))
    end
  end

  def close_event(conn, %{"id" => id}) do
    with event <- Events.get_event!(id, conn.assigns.current_user.id),
         {:ok, rule} <- Rules.check(Rules.from_event(event), :close_event),
         {:ok, _event} <- Events.update_event(event, %{"status" => rule.state}) do
      conn
      |> put_flash(:info, "Status verändert.")
      |> redirect(to: Routes.event_path(conn, :show, id))
    else
      :error ->
        conn
        |> put_flash(:error, "Not allowed.")
        |> redirect(to: Routes.event_path(conn, :show, id))
    end
  end

  defp check_if_organiser_or_scanner(conn, _params) do
    case is_scanner?(conn) || is_organiser?(conn) do
      true ->
        conn

      false ->
        conn
        |> redirect(to: "/events")
        |> halt()
    end
  end

  defp check_if_organiser(conn, _params) do
    case is_organiser?(conn) do
      true ->
        conn

      false ->
        conn
        |> redirect(to: "/events")
        |> halt()
    end
  end

  defp is_scanner?(%{params: %{"id" => event_id}} = conn) do
    with %{scanners: scanners} <- Events.get_event_with_preloads(event_id),
         user_id <- get_session(conn, :user_id),
         true <- user_in_scanners?(scanners, user_id) do
      true
    else
      _ ->
        false
    end
  end

  defp is_scanner?(_), do: false

  defp is_organiser?(%{params: %{"id" => event_id}} = conn) do
    case Events.get_event!(event_id, conn.assigns.current_user.id) do
      nil -> false
      _ -> true
    end
  end

  defp is_organiser?(_), do: false

  defp user_in_scanners?(scanners, user_id) do
    Enum.any?(scanners, fn %{id: id} -> id == user_id end)
  end
end

lib/visitor_tracking_web/views/event_view.ex
defmodule VisitorTrackingWeb.EventView do
  use VisitorTrackingWeb, :view

  use Timex

  def event_organiser?(conn, event) do
    conn.assigns.current_user.id == event.organiser_id
  end

  def datetime_convert(datetime) do
    datetime
    |> Timezone.convert("Europe/Zurich")
    |> Timex.format!("%Y-%m-%d um %R", :strftime)
  end
end

lib/visitor_tracking_web/templates/event/edit.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container">
    <div class="column">
      <h1 class="title">Veranstaltung bearbeiten</h1>
      <p class="subtitle"><%= @event.name%></p>
      <p class="buttons">
        <a class="button is-link is-outlined" href="<%= Routes.event_path(@conn, :index) %>">
          <span class="icon is-small">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Zurück</span>
        </a>
      </p>
    </div>
  </div>
	<div class="container">
	  <div class="column is-4">
	    <%= form_for @changeset, Routes.event_path(@conn, :update, @event), fn f ->	 %>

		    <div class="field">
		      <div class="control">
          <label class="label">Name</label>
            <%= text_input f, :name, class: "input is-medium", autofocus: "true" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :name %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Veranstaltungsort</label>
            <%= text_input f, :venue, class: "input is-medium" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :venue %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Besucher Limite</label>
            <%= text_input f, :visitor_limit, class: "input is-medium" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :visitor_limit %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Start</label>
            <div id="datetime-input"></div>
            <input type="hidden" name="datetime-tmp" value="<%= @event.date_start %>">
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :date_start %>
		     	</p>
		    </div>

        <%= submit "Veranstaltung speichern", class: "button is-block is-primary is-fullwidth is-medium" %>

      <% end %>
    </div>
  </div>
</section>

lib/visitor_tracking_web/templates/event/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :venue %>
  <%= text_input f, :venue %>
  <%= error_tag f, :venue %>

  <%= label f, :visitor_limit %>
  <%= text_input f, :visitor_limit %>
  <%= error_tag f, :visitor_limit %>

  <%= label f, :status %>
  <%= text_input f, :status %>
  <%= error_tag f, :status %>

  <%= label f, :closed %>
  <%= checkbox f, :closed %>
  <%= error_tag f, :closed %>

  <%= label f, :date_start %>
  <%= datetime_select f, :date_start %>
  <%= error_tag f, :date_start %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/visitor_tracking_web/templates/event/index.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container">
    <div class="column">
      <h1 class="title">Deine Veranstaltungen</h1>
      <p class="buttons">
        <a class="button is-link is-outlined" href="<%= Routes.event_path(@conn, :new) %>">
          <span class="icon is-small">
            <i class="fas fa-plus"></i>
          </span>
          <span>Neue Veranstaltung</span>
        </a>
      </p>
    </div>
  </div>
	<div class="container">
	  <div class="column">
	    <%= if @events == nil do %>
	    <p>Du hast bis jetzt noch keine Veranstaltung erstellt.</p>
	    <% else %>
	      <table class="table is-fullwidth">
          <thead>
            <tr>
              <th>Name</th>
              <th></th>
              <th>Besucher Limite</th>
              <th>Start</th>
            </tr>
          </thead>
          <tbody>
            <%= for event <- @events do %>
                <tr>
                  <td>
                    <a href="<%= Routes.event_path(@conn, :show, event) %>"><%= event.name %></a>
                  </td>
                  <td>
                    <span class="tag
                      <%= if event.status == "created" do %>is-primary<% end %>
                      <%= if event.status == "open" do %>is-success<% end %>
                      <%= if event.status == "closed" do %>is-warning<% end %>
                      <%= if event.status == "archived" do %><% end %>">
                      <%= event.status %></span>
                  </td>
                  <td><%= event.visitor_limit %></td>
                  <td><%= datetime_convert(event.date_start)  %></td>
                </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
	</div>
</section>

lib/visitor_tracking_web/templates/event/new.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container">
    <div class="column">
      <h1 class="title">Neue Veranstaltung</h1>
      <p class="buttons">
        <a class="button is-link is-outlined" href="<%= Routes.event_path(@conn, :index) %>">
          <span class="icon is-small">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Zurück</span>
        </a>
      </p>
    </div>
  </div>
	<div class="container">
	  <div class="column is-4">
	    <%= form_for @changeset, "/events", fn f ->	 %>

		    <div class="field">
		      <div class="control">
          <label class="label">Name</label>
            <%= text_input f, :name, class: "input is-medium", autofocus: "true" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :name %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Veranstaltungsort</label>
            <%= text_input f, :venue, class: "input is-medium" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :venue %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Besucher Limite</label>
            <%= text_input f, :visitor_limit, class: "input is-medium" %>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :visitor_limit %>
		     	</p>
		    </div>

		    <div class="field">
		      <div class="control">
          <label class="label">Start</label>
            <div id="datetime-input"></div>
		      </div>
		     	<p class="help is-danger">
		     		<%= error_tag f, :date_start %>
		     	</p>
		    </div>

        <%= submit "Veranstaltung erstellen", class: "button is-block is-primary is-fullwidth is-medium" %>

      <% end %>
	  </div>
  </div>
</section>

lib/visitor_tracking_web/templates/event/show.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container">
    <div class="column">
      <h1 class="title"><%= @event.name %></h1>
      <p class="subtitle"><%= datetime_convert(@event.date_start) %> @ <%= @event.venue %></p>
      <div class="tags has-addons">
        <span class="tag <%= if @event.status == "created" do %>is-primary<% end %>">Erstellt</span>
        <span class="tag <%= if @event.status == "open" do %>is-success<% end %>">Gestartet</span>
        <span class="tag <%= if @event.status == "closed" do %>is-warning<% end %>">Geschlossen</span>
        <span class="tag <%= if @event.status == "archived" do %><% end %>">Archiviert</span>
      </div>

      <%= if @emergency do %>
        <div class="notification is-danger">
          <strong>Ernstfall wurde eingeleitet:</strong> Daten geschickt an <%= @emergency.recipient_name %>, <%= @emergency.recipient_email %></strong>
        </div>
      <% end %>

      <%= if @event.status != "archived" do %>

        <h2 class="title is-4 mt-6">Aktionen</h2>

        <%= if @event.status == "closed" do %>
        <article class="message is-warning">
          <div class="message-body">
            Der Event wurde geschlossen. Es können <strong>keine Besucher</strong> mehr erfasst werden. Falls der Event noch nicht fertig ist kannst du ihn wieder öffnen.<br>
            <%= link to: Routes.event_path(@conn, :start_event, @event), class: "button is-info is-outlined" do %>
            <span>Event wieder öffnen</span>
            <% end %>
          </div>
        </article>
        <% end %>

        <p class="buttons">

        <%= if @event.status == "created" do %>
            <a class="button is-link is-outlined" href="<%= Routes.event_path(@conn, :edit, @event) %>">
              <span class="icon is-small">
                <i class="fas fa-edit"></i>
              </span>
              <span>Veranstaltung Bearbeiten</span>
            </a>

            <%= link to: Routes.event_path(@conn, :delete, @event), method: :delete, class: "button is-danger is-outlined", data: [confirm: "Wirklich löschen?"] do %>
              <span class="icon is-small">
                <i class="fas fa-times"></i>
              </span>
              <span>Veranstaltung Löschen</span>
            <% end %>
          <% end %>

          <%= if event_organiser?(@conn, @event) do %>
            <%= if @event.status != "closed" do %>
              <%= link to: "/events/#{@event.id}/scanners/new", class: "button is-primary is-outlined" do %>
                <span class="icon is-small">
                          <i class="fas fa-user-plus"></i>
                        </span>
                <span>Scanner hinzufügen</span>
              <% end %>
            <% end %>

            <%= if @event.status == "closed" do %>
              <%= if !@emergency do %>
                <%= link to: Routes.emergency_path(@conn, :new, @event.id), class: "button is-danger" do %>
                <span class="icon is-small">
                        <i class="fas fa-times"></i>
                      </span>
                <span>Ernstfall einleiten</span>
                <% end %>
              <% else %>
                  <em>Keine Aktionen möglich.</em>
              <% end %>
            <% end %>
          <% end %>

          <%= if @event.status == "open" do %>
            <%= link to: Routes.event_path(@conn, :close_event, @event), class: "button is-danger is-outlined", data: [confirm: "Event wirklich schliesse? Es können keine Besucher mehr reingelassen werden."] do %>
            <span class="icon is-small">
                      <i class="fas fa-times"></i>
                    </span>
            <span>Event schliessen</span>
            <% end %>
          <% end %>

          <%= if @event.status == "open" do %>
            <%= link to: Routes.scan_path(@conn, :show, @event), method: :get, class: "button is-link is-outlined", data: [confirm: "Mit dem Scannen starten?"] do %>
            <span class="icon is-small">
                <i class="fas fa-qrcode"></i>
              </span>
            <span>Scanner starten</span>
            <% end %>
          <% end %>

          <%= if @event.status == "created" do %>
            <%= link to: Routes.event_path(@conn, :start_event, @event), class: "button is-info is-outlined" do %>
            <span class="icon is-small">
                  <i class="fas fa-times"></i>
                </span>
            <span>Event starten</span>
            <% end %>
          <% end %>
        </p>
      <% end %>

      <h2 class="title is-4 mt-6">Besucher Übersicht</h2>
      <p><%= @visitors.active_visitors %> von <%= @event.visitor_limit %></p>
      <progress class="progress is-info" value="<%= @visitors.active_visitors %>" max="<%= @event.visitor_limit %>"></progress>
      <p>Total wurden an der Veranstaltung <%= @visitors.total_visitors %> Besucher registriert.</p>
    </div>
  </div>
</section>

<%= if @event.status != "archived" do %>
  <section class="mt-6">
    <div class="container">
      <div class="column">
        <h1 class="title is-4">Scanners</h1>
        <p class="subtitle">Hier kannst du Personen hinzufügen, welche die Besucher registrieren können. Die Personen müssen bei Vesita registriert sein.</p>
      </div>
    </div>
    <div class="container">
      <div class="column">
        <%= render(VisitorTrackingWeb.ScannerView, "index.html", %{ conn: @conn, current_user: @current_user, event_id: @event.id, scanners: @scanners, organiser: @event.organiser}) %>
      </div>
    </div>
  </section>
<% end %>

<section class="mt-6">
  <div class="container">
    <div class="column">
      <p class="buttons">
        <a class="button is-link is-outlined" href="<%= Routes.event_path(@conn, :index) %>">
          <span class="icon is-small">
            <i class="fas fa-arrow-left"></i>
          </span>
          <span>Zurück zur Übersicht</span>
        </a>
      </p>
    </div>
  </div>
</section>