lib/visitor_tracking_web/router.ex
defmodule VisitorTrackingWeb.Router do
  use VisitorTrackingWeb, :router

  use Plug.ErrorHandler
  use Sentry.Plug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VisitorTrackingWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug VisitorTrackingWeb.Plugs.Auth
  end

  pipeline :api do
    plug CORSPlug,
      origin: [
        "https://www.vesita.local:4001",
        "https://0.0.0.0:4001",
        "https://visitor-tracking-staging.gigalixirapp.com",
        "https://vesita-prod.herokuapp.com",
        "https://www.vesita.ch"
      ]

    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
  end

  scope "/", VisitorTrackingWeb do
    pipe_through :browser

    get "/", CmsController, :homepage
    get "/v/:token", ProfileController, :verify_email
    get "/datenschutz", CmsController, :privacy
    get "/preise", CmsController, :prices
    get "/impressum", CmsController, :impressum
    get "/so-einfach-funktioniert-vesita", CmsController, :howto
    get "/login", SessionController, :new
    post "/sessions", SessionController, :create
    get "/phone_validation", RegistrationController, :phone_validation
    post "/phone_confirmation", RegistrationController, :phone_confirmation
    get "/qr/:uuid", QrController, :show
    get "/kontakt", ContactFormController, :new
  end

  scope "/password/", VisitorTrackingWeb do
    pipe_through :browser
    get "/", PasswordController, :reset_password_request_form
    post "/", PasswordController, :reset_password_request
    get "/:token", PasswordController, :reset_password
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :check_registered]

    post "/register", RegistrationController, :new
    post "/users", RegistrationController, :create
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user]

    delete "/logout", SessionController, :delete
    get "/new_token", RegistrationController, :new_token
    get "/phone_verification", RegistrationController, :phone_verification
  end

  scope "/", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified]

    get "/expecting_verification", ProfileController, :expecting_verification
    resources "/events", EventController
    get "/events/:id/start_event", EventController, :start_event
    get "/events/:id/close_event", EventController, :close_event
    get "/events/:event_id/scan", ScanController, :show
    resources "/events/:event_id/emergency", EmergencyController, only: [:new, :create]
    get "/profile", ProfileController, :show
    get "/profile/qrcode", ProfileController, :show
  end

  scope "/events/:event_id/scanners", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]

    resources "/", ScannerController
  end

  scope "/events/:event_id/emergency", VisitorTrackingWeb do
    pipe_through [:browser, :authenticate_user, :check_phone_verified, :check_if_event_organiser]
    # resources "/", EmergencyController
  end

  # Other scopes may use custom stacks.
  scope "/api", VisitorTrackingWeb do
    pipe_through :api

    post "/scan/event_infos", ScanController, :event_infos
    post "/scan/user", ScanController, :user
    post "/scan/assign_visitor", ScanController, :assign_visitor
    post "/contact_forms/create", ContactFormController, :create
    post "/scan/insert_action", ScanController, :insert_action
    post "/registration/user", RegistrationApiController, :create
    post "/phone", RegistrationApiController, :verify_phone
    post "/password/reset", PasswordApiController, :reset_password
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:visitor_tracking, :developer_tools) == "true" do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: VisitorTrackingWeb.Telemetry
    end
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/visitor_tracking_web/controllers/cms_controller.ex
defmodule VisitorTrackingWeb.CmsController do
  use VisitorTrackingWeb, :controller

  use PhoenixMetaTags.TagController

  def homepage(conn, _) do
    conn
    |> put_meta_tags(%{
      title: "Effizientes Besucher-Tracking an deiner Veranstaltung | Vesita",
      description:
        "Vesita, die einfache und kostengünstige Lösung zur Erfassung der Besucherdaten an deiner Veranstaltung.",
      url: "https://www.vesita.ch",
      image:
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png",
      "og:image":
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png"
    })
    |> render("homepage.html", [])
  end

  def privacy(conn, _) do
    conn
    |> put_meta_tags(%{
      title: "Datenschutz | Vesita",
      description: "Datenschutz steht bei uns an oberster Stelle.",
      url: "https://www.vesita.ch",
      image:
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png",
      "og:image":
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png"
    })
    |> render("privacy.html", [])
  end

  def howto(conn, _) do
    conn
    |> put_meta_tags(%{
      title: "So einfach funktioniert Vesita | Vesita",
      description: "Einfach zu bedienen für Veranstalter und Besucher.",
      url: "https://www.vesita.ch",
      image:
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png",
      "og:image":
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png"
    })
    |> render("howto.html", [])
  end

  def prices(conn, _) do
    conn
    |> put_meta_tags(%{
      title: "Viele Vorteile für wenig Geld | Vesita",
      description:
        "Jeder Veranstaler soll sich Vesita leisten können. Keine Lizenz- oder Grundgebühren.",
      url: "https://www.vesita.ch",
      image:
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png",
      "og:image":
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png"
    })
    |> render("prices.html", [])
  end

  def impressum(conn, _) do
    conn
    |> put_meta_tags(%{
      title: "Impressum | Vesita",
      description: "Impressum.",
      url: "https://www.vesita.ch",
      image:
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png",
      "og:image":
        "https://" <>
          Application.get_env(:visitor_tracking, :host) <> "/images/vesita-logo-full-klein.png"
    })
    |> render("impressum.html", [])
  end
end

lib/visitor_tracking_web/views/cms_view.ex
defmodule VisitorTrackingWeb.CmsView do
  use VisitorTrackingWeb, :view
end

lib/visitor_tracking_web/templates/cms/homepage.html.eex
 <section class="hero is-medium is-info mb-6 bg-img">
   <div class="overlay">
    <div class="hero-head">
      <%= render(VisitorTrackingWeb.LayoutView, "navigation.html", %{conn: @conn, current_user: @current_user}) %>
    </div>
    <div class="hero-body">
      <div class="columns">
        <div class="column has-text-centered is-6 is-offset-3">
          <h1 class="title mb-6">Die einfache, innovative und kostengünstige Lösung zur Erfassung der Besucherdaten an deinen Veranstaltungen.
          </h1>
            <a href="<%= Routes.registration_path(@conn, :phone_validation) %>"><button class="button is-large is-inverted is-outlined is-primary">Jetzt Registrieren</button></a>
          </p>
        </div>
      </div>
    </div>
   </div>
</section>

<section>
  <div class="container">
    <%= render(VisitorTrackingWeb.LayoutView, "alert.html", conn: @conn) %>
  </div>
</section>

 <section>
   <div class="container mb-4">
     <div class="column is-8 is-offset-2 has-text-centered">
       <h2 class="title">Warum Vesita?</h2>
       <p class="subtitle mt-2">Sammle <strong>innert Sekunden</strong> die validierten Kontaktdaten deiner Gäste.<br><br>
         Jeder <strong>Besucher erhält einen persönlichen QR-Code</strong> und kann damit beliebig viele Veranstaltungen besuchen.<br><br>
         Unsere Auslagen decken wir mit einem <strong>Pay-As-You-Go</strong> Preismodell. Mehr Informationen findest du bei unseren <a href="<%= Routes.cms_path(@conn, :prices) %>">Preisen</a>.</p>
       <p>
         <a href="<%= Routes.cms_path(@conn, :howto) %>"><button class="button is-large is-outlined is-info">Zur Anleitung</button></a>
       </p>
      <div class="is-divider mt-6"></div>
     </div>
   </div>
 </section>


<section>
  <div class="container mb-4">
    <div class="column has-text-centered">
      <h2 class="title">
        Deine Vorteile
      </h2>
      <p class="subtitle is-4"></p>
    </div>
  </div>
  <div class="container">
    <div class="column">
      <ul class="featurelist">
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Kein Umsatzverlust durch ausfallende Besucher</h2>
          <p class="subtitle">Kann ein Gast die Veranstaltung nicht besuchen, so entsteht ein Konsumations-Umsatzverlust. Unsere Verifizierung ist <strong>nicht an ein Ticket gebunden</strong>. Der Besucher kann sein Ticket spontan an jemand anderen weitergeben.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Abendkasse möglich</h2>
          <p class="subtitle">Da eine Identifizierung über Vesita auch ohne personalisiertes Ticket möglich ist, können auch spontan an der Abendkasse noch Eintritte verkauft werden.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Minimaler Aufwand für den Veranstalter</h2>
          <p class="subtitle">Kein mühsames Verwalten von handgeschriebenen Zetteln oder Tabellen. Wir übernehmen die Verwaltung der Daten.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Keine Probleme mit dem Datenschutz</h2>
          <p class="subtitle">Per Gesetz müssen die personifizierten Daten innert 14 Tagen beim Veranstalter gelöscht werden. Der Veranstalter ist bei uns nie im Besitz der Daten. Jede Verbindung zum Event wird nach 14 Tagen gelöscht.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Check-In und Check-Out</h2>
          <p class="subtitle">Du kannst das <strong>Kommen und Gehen des Besuchers</strong> registrieren. So hast du jederzeit den Überblick, wieviele Personen sich gerade im Veranstaltungsgelände befinden.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Kleine und grosse Veranstaltungen</h2>
          <p class="subtitle">Vesita eignet sich für kleine Veranstaltungen (weniger als 100 Personen) aber auch für Grosse (über 1000 Personen)</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Kostenlose Demo</h2>
          <p class="subtitle">Du kannst Vesita an einer Veranstaltung bis max. 300 Peronen kostenlos testen.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            100% Transparent</h2>
          <p class="subtitle">Die Daten sind dem Veranstalter nicht zugänglich. Der Kunde hat zu jeder Zeit die <strong>Kontrolle über seine Daten</strong>.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Keine Lizenzkosten oder Abogebühren</h2>
          <p class="subtitle">Vesita ist für jeden User kostenlos. Als Veranstalter bezahlst du lediglich eine kleine Gebühr pro Besucher.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Effiziente Abwicklung</h2>
          <p class="subtitle">Unser Workflow ist simpel und erlaubt eine <strong>effiziente Abwicklung</strong> am Eingang zum Event.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Mehrere Eingänge möglich</h2>
          <p class="subtitle">Vesita erlaubt das Tracking an <strong>mehreren Eingängen gleichzeitig</strong>.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            Agiles Entwicklungsteam</h2>
          <p class="subtitle">Wir sind in der Lage, die Dienstleistung rasch den spontan wechelnden Bedingungen anzupassen.</p>
        </li>
        <li>
          <h2 class="colored is-5 is-primary">
            <figure>
              <i class="fa fa-check is-primary"></i>
            </figure>
            State-of-the-Art Technologie</h2>
          <p class="subtitle">Wir setzen auf <strong>Elixir</strong>, eine moderne und leistungsfähige Programmiersprache.</p>
        </li>
      </ul>
    </div>
  </div>
</section>

lib/visitor_tracking_web/templates/cms/howto.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container mb-4">
    <div class="column is-offset-3 is-6">
			<div class="content is-medium">
		    <h1 class="title has-text-centered">So einfach funktioniert Vesita!</h1>
		    <h2 class="title has-text-centered">Für Veranstalter</h2>
        <div class="timeline">
          <header class="timeline-header">
            <span class="tag is-medium is-primary">Start</span>
          </header>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">
            1
            </div>
            <div class="timeline-content">
              <p class="heading">Registrieren</p>
              <p>Du kannst dich auf unserer Seite <%= link "registrieren", to: Routes.registration_path(@conn, :phone_validation) %>.</p>
            </div>
          </div>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">
            2
            </div>
            <div class="timeline-content">
              <p class="heading">Eine Veranstaltung erstellen.</p>
              <p>Erstelle eine Verstanstaltung und füge beliebig viele <strong>Scanner</strong> hinzu. Ein Scanner ist eine Person, welcher <strong>das Kommen und Gehen des Besuchers mittels QR-Codes erfasst</strong>. Du kannst zum Beispiel 2 Scanner beim Eingang haben und einen Scanner beim Ausgang, der die Besucher wieder abmeldet. Um den QR-Code zu erfassen benötigt jeder Scanner ein gängiges Smartphone (Android / iOS).</p>
            </div>
          </div>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">
            3
            </div>
            <div class="timeline-content">
              <p class="heading">Die Veranstaltung beginnt.</p>
              <p>Am Veranstaltungstag eröffnest du die Veranstaltung und schon sind die Scanner bereit, die Besucher über die Webapplikation zu erfassen.</p>
            </div>
          </div>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">
              4
            </div>
            <div class="timeline-content">
              <p class="heading">Die Veranstaltung endet.</p>
              <p>Du schliesst den Event wieder, worauf keine weiteren Gäste mehr erfasst werden können.</p>
            </div>
          </div>
          <header class="timeline-header">
            <span class="tag is-warning">Ernstfall</span>
          </header>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">

            </div>
            <div class="timeline-content">
              <p class="heading">Ein Gast ist COVID19 positiv.</p>
              <p>Im Ernstfall kannst du die Gästeliste über unsere Plattform direkt an den kantonsärztlichen Dienst weiterleiten lassen.</p>
            </div>
          </div>
          <header class="timeline-header">
            <span class="tag is-info">Nach 14 Tagen</span>
          </header>
          <div class="timeline-item">
            <div class="timeline-marker is-image is-32x32 has-text-centered">

            </div>
            <div class="timeline-content">
              <p class="heading">14 Tage nach dem Ende der Veranstaltung.</p>
              <p>Jegliche Verbindung zur Veranstaltung wird entfernt.</p>
            </div>
          </div>
          <div class="timeline-header">
            <span class="tag is-medium is-primary">Ende</span>
          </div>
        </div>

        <div class="is-divider mt-6"></div>

        <h2 class="title has-text-centered mt-6">Für Besucher</h2>
          <div class="timeline">
            <header class="timeline-header">
              <span class="tag is-medium is-primary">Start</span>
            </header>
            <div class="timeline-item">
              <div class="timeline-marker is-image is-32x32 has-text-centered">
              1
              </div>
              <div class="timeline-content">
                <p class="heading">Registrieren</p>
                <p>Du kannst dich auf unserer Seite <%= link "registrieren", to: Routes.registration_path(@conn, :phone_validation) %>.</p>
              </div>
            </div>
            <div class="timeline-item">
              <div class="timeline-marker is-image is-32x32 has-text-centered">
              2
              </div>
              <div class="timeline-content">
                <p class="heading">Erfolgreiche Registierung.</p>
                <p>Nach Abschluss der Registrierung erhälst du eine SMS mit einem QR-Code.</p>
              </div>
            </div>
            <div class="timeline-item">
              <div class="timeline-marker is-image is-32x32 has-text-centered">
              3
              </div>
              <div class="timeline-content">
                <p class="heading">Die Veranstaltung beginnt.</p>
                <p>Du kannst deinen QR-Code zusammen mit einer gültigen ID beim Eingang vorweisen. Der Veranstalter sieht beim Scannen deines Codes kurzfristig deinen Namen. Er kann aber zu keiner Zeit nachsehen, wer an seiner Veranstaltung war.</p>
              </div>
            </div>
            <div class="timeline-item">
              <div class="timeline-marker is-image is-32x32 has-text-centered">
                4
              </div>
              <div class="timeline-content">
                <p class="heading">Die Veranstaltung endet.</p>
                <p>Du verlässt die Veranstaltung - dein Code bleibt gültig. Beim nächsten Mal kannst du ihn erneut vorzeigen.</p>
              </div>
            </div>
             <header class="timeline-header">
               <span class="tag is-warning">Ernstfall</span>
             </header>
             <div class="timeline-item">
               <div class="timeline-marker is-image is-32x32 has-text-centered">

               </div>
               <div class="timeline-content">
                 <p class="heading">Ein Gast ist COVID19 positiv.</p>
                 <p>Im Ernstfall kann der Veranstalter deine Personalien direkt an die kantonsärztlichen Dienste weiterleiten lassen. Du wirst dabei per E-Mail informiert. Bitte beachte, dass du deine E-Mail-Adresse bei der Registrierung validiert hast (wir schicken dir dazu eine E-Mail mit einem Aktivierungslink).</p>
               </div>
             </div>
             <header class="timeline-header">
               <span class="tag is-info">Nach 14 Tagen</span>
             </header>
             <div class="timeline-item">
               <div class="timeline-marker is-image is-32x32 has-text-centered">

               </div>
               <div class="timeline-content">
                 <p class="heading">14 Tage nach dem Ende der Veranstaltung.</p>
                 <p>Jegliche Verbindung zur Veranstaltung wird entfernt. Dein Profil bleibt bestehen. Niemand kann mehr nachvollziehen, wer die Veranstaltung besucht hat.</p>
               </div>
             </div>
            <div class="timeline-header">
              <span class="tag is-medium is-primary">Ende</span>
            </div>
          </div>
		  </div>
    </div>
  </div>
</section>

lib/visitor_tracking_web/templates/cms/impressum.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container mb-4">
    <div class="column is-offset-3 is-6">
			<div class="content is-medium">
		    <h1 class="title has-text-centered">Impressum</h1>
        <h2 class="is-1">Idee, Konzept, Management, Entwicklung</h2>
        <p><a href="https://www.linkedin.com/in/simon-kistler-85648084/">Simon Kistler</a>, 5200 Brugg</p>
        <h2 class="is-1">Konzept, Entwicklung</h2>
        <p><a href="https://www.linkedin.com/in/george-mantzouranis-38203028/">George Mantzouranis</a></p>
        <h2>Many thanks to</h2>
        <p>Dario Ghilardi (Frontend / Backend Entwicklung)</p>
        <p>Alessandro Di Maria (Backend Entwicklung)</p>
        <p></p>
        <p class="mt-6">Bitte nutze unser <a href="/kontakt">Kontaktformular</a>.</p>
		  </div>
    </div>
  </div>
</section>

lib/visitor_tracking_web/templates/cms/prices.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container mb-4">
    <div class="column is-offset-3 is-6">
			<div class="content is-medium has-text-centered">
		    <h1 class="title">So wenig kostet Vesita!</h1>
        <p>Wir verkaufen keine Daten und machen auch keine Werbung für andere Systeme. Mit den Einnahmen versuchen wir Infrastruktur und Entwicklungskosten zu decken.</p>
        <p>Unser Ziel ist es, dass sich jeder Veranstalter ein zuverlässiges und einfaches Contact-Tracing leisten kann. Du bezahlst nur was du brauchst. Die Preise gelten pro Veranstaltung.</p>
        <p>
            Keine Abogebühren <span class="is-success"><i class="fa fa-check is-primary"></i></span>
        </p>
        <p>
          Keine Lizenzkosten <span class="is-success"><i class="fa fa-check is-primary"></i></span>
        </p>
        <p></p>
        <p>
            Keine Mindestkosten <span class="is-success"><i class="fa fa-check is-primary"></i></span>
        </p>
        <div class="pricing-table">
          <div class="pricing-plan is-active">
            <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">CHF</span>0.49</span>/Besucher</div>
            <div class="plan-items">
              <div class="plan-item">Für neue Registrationen</div>
            </div>
          </div>
          <div class="pricing-plan is-active">
            <div class="plan-price"><span class="plan-price-amount"><span class="plan-price-currency">CHF</span>0.29</span>/Besucher</div>
            <div class="plan-items">
              <div class="plan-item">Für wiederkehrende Gäste.<br>Falls sich der Gast bereits einmal bei uns Registriert hat.</div>
            </div>
          </div>
        </div>
		  </div>
    </div>
  </div>
</section>

lib/visitor_tracking_web/templates/cms/privacy.html.eex
<%= render(VisitorTrackingWeb.LayoutView, "header.html", %{conn: @conn, current_user: @current_user}) %>

<section>
  <div class="container mb-4">
    <div class="column">
			<div class="content is-medium">
		    <h1 class="title">Datenschutzrichtlinien</h1>
		   	<p class="subtitle">Stand: 2020-07-14</p>
		    <h2 class="is-2">Welche personenbezogenen Daten wir sammeln und warum wir sie sammeln</h2>
		    <h3>Allgemeine Daten</h3>
		    <p>Wenn Sie auf diese Webseite zugreifen werden automatisch Informationen allgemeiner Natur erfasst. Diese Informationen werden im Server-Logfile erfasst und beinhalten die Art des Webbrowsers, das verwendete Betriebssystem, den Domainnamen Ihres Internet-Service-Providers, Ihre IP-Adresse und ähnliches.</p>
<p>Dies aus folgendem Grund:
	<ul>
<li>Sicherstellung eines problemlosen Verbindungsaufbaus der Website</li>
<li>Sicherstellung einer reibungslosen Nutzung unserer Website</li>
<li>Auswertung der Systemsicherheit und -stabilität sowie</li>
<li>zu weiteren administrativen Zwecken</li>
</ul></p>
<p>Ihre Daten werden nicht verwendet, um Rückschlüsse auf Ihre Person zu ziehen. Informationen dieser Art werden lediglich statistisch ausgewertet, um unseren Internetauftritt und die dahinterstehende Technik zu optimieren.</p>

<h3>Personenbezogene Daten</h3>
<p>Alle persönlichen Daten sie sie in ihrem Profil angegeben haben werden gespeichert. Dies dient dazu, dass dem kantonsärztlichen Dienst im Falle einer bekannten Infektion eine Liste aller Besucher übermittelt werden kann.</p>

<h2>Speicherdauer von Daten</h2>
<p>Für Benutzer, die sich auf unserer Website registrieren, speichern wir zusätzlich die persönlichen Informationen, die sie in ihren Benutzerprofilen angeben. Alle Benutzer können jederzeit ihre persönlichen Informationen einsehen, verändern oder löschen (nur per E-Mail Anfrage -> Rechtliche Grundlagen beachten).</p>
<p>Alle personenbezogenen Daten müssen per Gesetz während 14 Tagen nach der letzten Anmeldung an einem Event gespeichert werden. Nach dem Ablauf dieser Frist löschen wir in jedem Fall die Verknüpfung ihrer Daten zu einem Event.</p>

<h2>Wer hat Einsicht in ihre Daten</h2>
<p>Der Veranstalter kann ihre Daten zu keiner Zeit auslesen. Lediglich beim Scannen des QR Codes wird ihr Name kurz erscheinen. Dies dient zur Identifikation zusammen mit der ID.</p>
<p>Der kantonsärztliche Dienst kann per Gesetz eine Liste aller Gäste inklusive Kontaktdaten anfordern. Sollten wir aufgefordert werden ihre Daten auszuhändigen, werden sie von uns per E-Mail informiert.</p>

<h2>Datenübertragung</h2>
<p>Um die Sicherheit Ihrer Daten bei der Übertragung zu schützen, verwenden wir dem aktuellen Stand der Technik entsprechende Verschlüsselungsverfahren (z. B. SSL) über HTTPS.</p>

<h2>SMS und E-Mail Gateway</h2>
<p>Wir übermitteln lediglich die E-Mail-Adresse und den Vornamen per E-Mail. Als Gateway nutzen wir <a href="https://sendgrid.com/" target="_blank">SendGrid</a> von Twilio</p>
<p>Da SMS prinzipiell ein unsicheres Kommunikationsmittel ist, verzichten wir auf das übermitteln von personifizierten Daten. SMS werden nur für das übermitteln der Verifizierungstokens und für die Bestätigung der Registrierung verwendet. Für die Übermittlung der SMS verwenden wir wiederum Twilio.</p>
<p>
	Informationen über Twilio / SendGrid
<ul>
	<li><a href="https://www.twilio.com/legal/tos#4-customer-data" target="_blank">Datenschutz</a></li>
	<li><a href="https://www.twilio.com/security" target="_blank">Sicherheit</a></li>
</ul>
</p>
		  </div>
    </div>
  </div>
</section>